### ISSUE TITLE
Arquitectura del Sistema

### ISSUE THREAD

**Issue by JUNIORRDSR** [Curcolor/COMMUNITY#12]
> [!IMPORTANT]
> Hay que realizar la arquitectura completa del sistema para empezar a definir que partes del sistema se hacen primero y como nos vamos a repartir el trabajo.

**Comment by JUNIORRDSR** [comment]
> [!NOTE]
> Por ahora esta es mi propuesta de como se vería la [arquitectura del Proyecto ](https://app.diagrams.net/#G11zqifh6wNKNGMGq4sm0fXmQfJhte6ptM#%7B%22pageId%22%3A%22eoxBPnK1w82H6C3VRJOZ%22%7D), obviamente necesita ser rediseñada para presentarse ante los docentes.

**Comment by JUNIORRDSR** [comment]
> [!IMPORTANT]
> @Curcolor, @SaryNotfound y @DANN-MAGE, necesito que opinen o presenten sus propuestas para poder avanzar en el desarrollo de los microservicios.

**Comment by Curcolor** [comment]
@JUNIORRDSR okey, en el diseño no se ve de forma explícita las apis externas que necesitamos. Por otro lado, la base de datos de notificación no me parece, hoy presento una propuesta.

**Comment by Curcolor** [comment]
> [!IMPORTANT]
> Creo que esta es una propuesta solida para ser analizada y rediseñada para presentar en [arquitectura del Proyecto ]
(https://app.diagrams.net/#G11zqifh6wNKNGMGq4sm0fXmQfJhte6ptM#%7B%22pageId%22%3A%22eoxBPnK1w82H6C3VRJOZ%22%7D), 

![Image](https://github.com/user-attachments/assets/5244906d-b73e-450b-8778-b3b8e389bf7f)

**Comment by JUNIORRDSR** [comment]
@Curcolor Creo que el diseño es claro y sigue el modelo propuesto inicialmente. Lo único que se debe considerar es la sección de las bases de datos para asegurar una buena coordinación en la creación de ese aspecto. Por lo demás, todo me parece muy bien.

**Comment by Curcolor** [comment]
Teniendo en cuenta las recomendaciones de @JUNIORRDSR actualizo el diseño que muestra en la [arquitectura del Proyecto](https://app.diagrams.net/#G11zqifh6wNKNGMGq4sm0fXmQfJhte6ptM#%7B%22pageId%22%3A%22eoxBPnK1w82H6C3VRJOZ%22%7D). A continuación una imagen, pero lo mejor sería verlo en drawio.

![Captura de pantalla 2024-11-08 123530](https://github.com/user-attachments/assets/55e2656e-c4f4-440d-89d0-ba640a258c0b)

**Comment by JUNIORRDSR** [comment]
> [!NOTE]
> La Arquitectura Presentada cumple con el modelo que se tiene del sistema, este será modificado futuramente para presentarse formalmente.
