### ISSUE TITLE
Base de Datos Usuarios

### ISSUE THREAD

**Issue by JUNIORRDSR** [Curcolor/COMMUNITY#14]
> [!note]
> Crearé la estructura de la base de datos para luego darle funcionamiento en términos de pruebas mientras espero la integración de próximas bases de datos que se propongan

**Comment by JUNIORRDSR** [comment]
# Base de Datos Usuarios
El sistema debe ofrecer un formulario de registro con los siguientes ítems: Cedula, Nombre, Teléfono, Email, Sexo, País, Ciudad, Contraseña y Fecha de Nacimiento.  Además, cada usuario debe poder acceder a una lista de sus programas favoritos y a un historial de los servicios de ayuda que ha solicitado.

Los usuarios que elijan ser voluntarios deben elegir una o varias categorías en las que se sienten preparados para brindar asistencia, como educación, salud, asesoría legal, entre otras, estos pueden ofrecer una descripción donde especifiquen los servicios que están dispuestos a ofrecer en cada área de especialización, proporcionando detalles sobre cómo pueden ayudar y el por qué el interés detrás de ello si le interesa, pueden especificar si ofrecen ayuda presencial o solo a distancia, además de la ubicación en caso de servicios presenciales.

Los voluntarios tendrán la capacidad de crear publicaciones relacionadas con eventos o actividades de ayuda. Esto incluye:

1. Crear eventos: Los voluntarios pueden crear eventos públicos o privados para anunciar actividades de voluntariado específicas donde ofrezcan sus servicios (por ejemplo, jornadas de salud, talleres educativos, eventos comunitarios), con la opción de incluir:

- 	  Fecha y hora del evento: Definir cuándo se llevará a cabo.

-	  Descripción del evento: Explicar los objetivos, la ayuda ofrecida, y a quienes va dirigida.

-	  Ubicación: Definir si el evento es presencial o en línea, y especificar la ubicación o el enlace.

2. Crear solicitudes de ayuda: Los voluntarios pueden genera solicitudes cuando estén dispuestos a ayudar, indicando:

-	  Tipo de servicio ofrecido.

-	  Descripción de la ayuda.

-	  Ubicación (si aplica).

-	  Duración o tiempo estimado de la ayuda.

3. Puntuaciones y calificaciones: Se implementará un sistema de puntuación para calificar el compromiso y desempeño de los voluntarios dentro de la comunidad. Esto incluye:

-	   Puntuación general: Cada voluntario recibirá una calificación general basada en, el número de personas atendidas y la satisfacción de los usuarios a los que ha ayudado.

-	   Calificaciones individuales: Después de cada interacción, los usuarios que recibieron ayuda pueden dejar una calificación (por ejemplo, de 1 a 5 estrellas) sobre el servicio prestado por el voluntario.

Comentarios sobre el servicio:

-	   El sistema permitirá que los usuarios de la plataforma dejen comentarios y reseñas sobre los voluntarios.
- 	   Comentarios y retroalimentación: Además de la puntuación, los usuarios pueden dejar comentarios adicionales sobre su experiencia, destacando aspectos positivos o sugerencias de mejora para el voluntario.

![Base de datos Usuarios Voluntarios](https://github.com/user-attachments/assets/48de6b79-db8d-4431-8497-ec85223c9746)

> [!note]
> En las tablas 'favoritos' e 'historial' se tiene una columna llamada 'programa_id', esta es una columna que hace referencia a una tabla de programas que no se ha modelado en esta base de datos por que se piensa insertar en otra

**Comment by Curcolor** [comment]
@JUNIORRDSR pues teniendo en cuenta solo es el diseño del la base de datos de usuarios, el "programa_id" será unos daros externos fuera de eso esta perfecto.

**Comment by JUNIORRDSR** [comment]
> [!IMPORTANT]
> Se presenta el modelo Final Relacional que hará parte de la base de datos de los usuarios [bd-community.pdf](https://github.com/user-attachments/files/17794383/bd-community.pdf)
