### ISSUE TITLE
Documento de Requerimientos del sistema ERS

### ISSUE THREAD

**Issue by Curcolor** [Curcolor/COMMUNITY#7]
El archivo tiene esta casi completado solo falta dos diagramas, **caso de uso y la arquitectura general del sistema**

[ERS-SOFTWAREII-COMMUNITY-REVISON_01-MODIFI_00.docx](https://github.com/user-attachments/files/17609397/ERS-SOFTWAREII-COMMUNITY-REVISON_01-MODIFI_00.docx)

**Comment by JUNIORRDSR** [comment]
> [!WARNING]
> El documento **no esta completo** con los avances de los participantes, lo que tiene es una plantilla de como se vería y su estructura básica.
> A este le falta especificar que microservicios llevará nuestro sistema y como integrarlos con el **Patrón MVC** propuesto por los participantes.

**Comment by JUNIORRDSR** [comment]
> [!NOTE]
> Integré las parte de @SaryNotfound y mí (@JUNIORRDSR ), falta aún verificar si la parte de @Curcolor  y @DANN-MAGE están al día, añadir las funcionalidades de cada microservicio,  como se conectan entre si, sus diagramas de clases y las APIs  que usaremos.
[ERS-SOFTWAREII-COMMUNITY-REVISON_01-MODIFI_01docx](https://github.com/user-attachments/files/17644045/ERS-SOFTWAREII-COMMUNITY-REVISON_01-MODIFI_00.docx)

**Comment by JUNIORRDSR** [comment]
> [!IMPORTANT]
> Subo la ultima modification por mi parte del documento [ERS-SOFTWAREII-COMMUNITY-REVISON_01-MODIFI_02.pdf](https://github.com/user-attachments/files/17794357/ERS-SOFTWAREII-COMMUNITY-REVISON_01-MODIFI_02.pdf)

**Comment by JUNIORRDSR** [comment]
> faltan las imágenes finales porque lo cierras? @JUNIORRDSR, por último, gracias por aportar.

Cierro por que durante la iteration no se presentaron mas cambios y no se hablo acerca de alguno a futuro.

**Comment by Curcolor** [comment]
@JUNIORRDSR en el ERS se ve una imagen representativa de falta de recursos (casos de uso y arquitectura), obvio pues es algo que aún no tenemos estilizado para el ERS 
Una imagen de lo que me refiero: 
![image](https://github.com/user-attachments/assets/d5faaf24-c7ed-4f3e-8833-dde8132def36)

**Comment by JUNIORRDSR** [comment]
> [!IMPORTANT]
> ULTIMA MODIFICACION DEL  [DOCUMENTO ERS](https://github.com/user-attachments/files/17992914/Documento.ERS.pdf)
